### PR TITLE
Cmg tools from cmssw 7 4 7 for puppi

### PR DESCRIPTION
**Pull request by gitytakahas**

### CODE REVIEW

**Comment by gitytakahas** [comment]
I built my update on top of CMSSW_7_4_7, so this is probably not the right thing to do ... in that case, just reject this PR.

**Comment by steggema** [comment]
There are conflicts - can you try to merge once more from this branch locally and update the PR?

**Comment by steggema** [comment]
Or you may directly want to rebase this PR on 747

**Comment by gitytakahas** [comment]
oh sorry I forgot about this...
I think the most easiest way would be, you copy,

CMGTools/H2TauTau/cfgPython/
https://github.com/gitytakahas/cmg-cmssw/commit/7fce0bb99e7c4b1d26b2bd3b3b7eae8e4d5ea61d#diff-4956d2975d30d9fb8880bd8ba4e18957
et/tauEle_2015_cmssw_cfg
https://github.com/gitytakahas/cmg-cmssw/commit/7fce0bb99e7c4b1d26b2bd3b3b7eae8e4d5ea61d#diff-c75c9b4d2754a76ee0c85fb141857313
.py
https://github.com/gitytakahas/cmg-cmssw/commit/7fce0bb99e7c4b1d26b2bd3b3b7eae8e4d5ea61d#diff-4956d2975d30d9fb8880bd8ba4e18957
CMGTools/H2TauTau/python/proto/analyzers/ElectronIsolationCalculator.py
https://github.com/gitytakahas/cmg-cmssw/commit/7fce0bb99e7c4b1d26b2bd3b3b7eae8e4d5ea61d#diff-4956d2975d30d9fb8880bd8ba4e18957
https://github.com/gitytakahas/cmg-cmssw/commit/7fce0bb99e7c4b1d26b2bd3b3b7eae8e4d5ea61d#diff-04b9dac864b9b76fb1362958cf67c62bCMGTools/H2TauTau/python/proto/analyzers/H2TauTauTreeProducerTauEle.py

I put them at /afs/cern.ch/user/y/ytakahas/public/forJan
you can simply replace (or copy) them ?
If you agree ...

Y.

2015-08-20 17:50 GMT+02:00 Jan Steggemann notifications@github.com:

> Or you may directly want to rebase this PR on 747
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/steggema/cmg-cmssw/pull/4#issuecomment-133057905.

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by steggema** [comment]
Can you check this commit https://github.com/steggema/cmg-cmssw/commit/141c32d7d2bfee583882ee389a3d109887f7f56d

**Comment by steggema** [comment]
Since I merged it manually into another branch, I'm closing this PR.

**Pull request closed without merging**
